### ISSUE TITLE
java.lang.RuntimeException: Compilation failed.

### ISSUE THREAD

**Issue by shenhuaxx** [declife/compiler#1]
idea里面启动工程后，调用/test/liu 可以正常返回。

mvn clean package之后,java -jar error-1.0-SNAPSHOT.jar,启动工程，
调用/test/liu 就出现java.lang.RuntimeException: Compilation failed.编译不过
```
/DynamicClass.java:3: error: package com.alibaba.fastjson does not exist
import com.alibaba.fastjson.JSONObject;import com.liu.test.compile.on.DynamicInterface;import java.util.Map;
                           ^
/DynamicClass.java:3: error: package com.liu.test.compile.on does not exist
import com.alibaba.fastjson.JSONObject;import com.liu.test.compile.on.DynamicInterface;import java.util.Map;
                                                                     ^
/DynamicClass.java:5: error: cannot find symbol
public class DynamicClass implements DynamicInterface {
                                     ^
  symbol: class DynamicInterface
/DynamicClass.java:7: error: method does not override or implement a method from a supertype
       @Override
       ^
4 errors
java.lang.RuntimeException: Compilation failed.
	at com.liu.test.compile.JavaStringCompiler.compile(JavaStringCompiler.java:62)
	at com.liu.test.compile.service.service.hello(service.java:27)
	at com.liu.test.controller.TestController.hello(TestController.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

**Comment by shenhuaxx** [comment]
idea 运行时Parent Classloader
```
TomcatEmbeddedWebappClassLoader
  context: ROOT
  delegate: true
----------> Parent Classloader:
sun.misc.Launcher$AppClassLoader@18b4aac2
```

命令行jar包运行时Parent Classloader
```
TomcatEmbeddedWebappClassLoader
  context: ROOT
  delegate: true
----------> Parent Classloader:
org.springframework.boot.loader.LaunchedURLClassLoader@439f5b3d
```

**Comment by declife** [comment]
> idea里面启动工程后，调用/test/liu 可以正常返回。
> 
> mvn clean package之后,java -jar error-1.0-SNAPSHOT.jar,启动工程，
> 调用/test/liu 就出现java.lang.RuntimeException: Compilation failed.编译不过
> 
> ```
> /DynamicClass.java:3: error: package com.alibaba.fastjson does not exist
> import com.alibaba.fastjson.JSONObject;import com.liu.test.compile.on.DynamicInterface;import java.util.Map;
>                            ^
> /DynamicClass.java:3: error: package com.liu.test.compile.on does not exist
> import com.alibaba.fastjson.JSONObject;import com.liu.test.compile.on.DynamicInterface;import java.util.Map;
>                                                                      ^
> /DynamicClass.java:5: error: cannot find symbol
> public class DynamicClass implements DynamicInterface {
>                                      ^
>   symbol: class DynamicInterface
> /DynamicClass.java:7: error: method does not override or implement a method from a supertype
>        @Override
>        ^
> 4 errors
> java.lang.RuntimeException: Compilation failed.
> 	at com.liu.test.compile.JavaStringCompiler.compile(JavaStringCompiler.java:62)
> 	at com.liu.test.compile.service.service.hello(service.java:27)
> 	at com.liu.test.controller.TestController.hello(TestController.java:23)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> ```

看报错像是依赖没下下来，fastjson没找到

**Comment by shenhuaxx** [comment]
你本地这么跑没问题吗？

我改了点东西，打包后再运行就OK了。
```
MemoryJavaFileManager manager = new MemoryJavaFileManager(stdManager, new TomcatEmbeddedWebappClassLoader())

改为了

ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
MemoryJavaFileManager manager = new MemoryJavaFileManager(stdManager, classLoader);
```

**Comment by declife** [comment]
> 你本地这么跑没问题吗？
> 
> 我改了点东西，打包后再运行就OK了。
> 
> ```
> MemoryJavaFileManager manager = new MemoryJavaFileManager(stdManager, new TomcatEmbeddedWebappClassLoader())
> 
> 改为了
> 
> ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
> MemoryJavaFileManager manager = new MemoryJavaFileManager(stdManager, classLoader);
> ```

我是用在一个微服务里，是通过这个来取classloder的(这里面是从调用接口的地方拿到的上下文classloader)
MemoryJavaFileManager manager = new MemoryJavaFileManager(stdManager, SpringUtil.getTomcatClassLoader())

**Comment by shenhuaxx** [comment]
> > 你本地这么跑没问题吗？
> > 我改了点东西，打包后再运行就OK了。
> > ```
> > MemoryJavaFileManager manager = new MemoryJavaFileManager(stdManager, new TomcatEmbeddedWebappClassLoader())
> > 
> > 改为了
> > 
> > ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
> > MemoryJavaFileManager manager = new MemoryJavaFileManager(stdManager, classLoader);
> > ```
> 
> 我是用在一个微服务里，是通过这个来取classloder的(这里面是从调用接口的地方拿到的上下文classloader)
> MemoryJavaFileManager manager = new MemoryJavaFileManager(stdManager, SpringUtil.getTomcatClassLoader())

那就是了 你看仓库的代码 JavaStringCompiler.java 第45行，传入的是new TomcatEmbeddedWebappClassLoader()。
所以我初始clone下来打包跑不通，后来改为传入Thread.currentThread().getContextClassLoader()就OK了
